using Godot;
using MegaCrit.Sts2.Core.Models;

namespace WatcherMod;

public sealed class WatcherV2CardPool : CardPoolModel
{
	public override string Title => "watcher";

	public override string EnergyColorName => "watcher";

	public override string CardFrameMaterialPath => "card_frame_purple";

	public override Color DeckEntryCardColor => new Color("9E68FF");

	public override bool IsColorless => false;

	protected override CardModel[] GenerateAllCards()
	{
		return new CardModel[140]
		{
			ModelDb.Card<Strike_P>(),
			ModelDb.Card<Defend_P>(),
			ModelDb.Card<Conviction>(),
			ModelDb.Card<Prescience>(),
			ModelDb.Card<Eruption_P>(),
			ModelDb.Card<Vigilance>(),
			ModelDb.Card<BowlingBash>(),
			ModelDb.Card<Consecrate>(),
			ModelDb.Card<Crescendo>(),
			ModelDb.Card<CutThroughFate>(),
			ModelDb.Card<EmptyBody>(),
			ModelDb.Card<EmptyFist>(),
			ModelDb.Card<Evaluate>(),
			ModelDb.Card<FlyingSleeves>(),
			ModelDb.Card<Halt>(),
			ModelDb.Card<JustLuckyV2>(),
			ModelDb.Card<Prostrate>(),
			ModelDb.Card<Protect>(),
			ModelDb.Card<ThirdEyeV2>(),
			ModelDb.Card<Tranquility>(),
			ModelDb.Card<ColdObservation>(),
			ModelDb.Card<Mockery>(),
			ModelDb.Card<Persuasion>(),
			ModelDb.Card<CarveReality>(),
			ModelDb.Card<Conclude>(),
			ModelDb.Card<DeceiveReality>(),
			ModelDb.Card<EmptyMind>(),
			ModelDb.Card<Fasting2>(),
			ModelDb.Card<FearNoEvil>(),
			ModelDb.Card<ForeignInfluence>(),
			ModelDb.Card<ForesightV2>(),
			ModelDb.Card<Indignation>(),
			ModelDb.Card<InnerPeace>(),
			ModelDb.Card<Meditate>(),
			ModelDb.Card<MentalFortress>(),
			ModelDb.Card<NirvanaV2>(),
			ModelDb.Card<Perseverance>(),
			ModelDb.Card<Pray>(),
			ModelDb.Card<Rushdown>(),
			ModelDb.Card<Sanctity>(),
			ModelDb.Card<SandsOfTime>(),
			ModelDb.Card<SignatureMove>(),
			ModelDb.Card<SimmeringFury>(),
			ModelDb.Card<Study>(),
			ModelDb.Card<SwivelV2>(),
			ModelDb.Card<TalkToTheHand>(),
			ModelDb.Card<Tantrum>(),
			ModelDb.Card<Wallop>(),
			ModelDb.Card<Weave>(),
			ModelDb.Card<WheelKick>(),
			ModelDb.Card<WindmillStrike>(),
			ModelDb.Card<Worship>(),
			ModelDb.Card<WreathOfFlame>(),
			ModelDb.Card<Revelation>(),
			ModelDb.Card<Hymn>(),
			ModelDb.Card<Relinquish>(),
			ModelDb.Card<Sanctification>(),
			ModelDb.Card<Blasphemy>(),
			ModelDb.Card<Brilliance>(),
			ModelDb.Card<DeusExMachina>(),
			ModelDb.Card<DevaForm>(),
			ModelDb.Card<Devotion>(),
			ModelDb.Card<Establishment>(),
			ModelDb.Card<JudgmentV2>(),
			ModelDb.Card<LessonLearned>(),
			ModelDb.Card<MasterReality>(),
			ModelDb.Card<Omniscience>(),
			ModelDb.Card<Ragnarok>(),
			ModelDb.Card<Scrawl_P>(),
			ModelDb.Card<SpiritShield>(),
			ModelDb.Card<Vault>(),
			ModelDb.Card<WishV2>(),
			ModelDb.Card<Cataclysm>(),
			ModelDb.Card<Serenity>(),
			ModelDb.Card<Preach>(),
			ModelDb.Card<DrawTalisman>(),
			ModelDb.Card<Miracle>(),
			ModelDb.Card<ProphetForm>(),
			ModelDb.Card<ControlPast>(),
			ModelDb.Card<Foreknowledge>(),
			ModelDb.Card<Confidence>(),
			ModelDb.Card<AnswerQuestion>(),
			ModelDb.Card<Powerlessness>(),
			ModelDb.Card<DeepThought>(),
			ModelDb.Card<EvictGuest>(),
			ModelDb.Card<Formation>(),
			ModelDb.Card<Foretell>(),
			ModelDb.Card<GuessAttack>(),
			ModelDb.Card<GuessDebuff>(),
			ModelDb.Card<GuessCardDebuff>(),
			ModelDb.Card<GuessStatus>(),
			ModelDb.Card<GuessDefend>(),
			ModelDb.Card<GuessBuff>(),
			ModelDb.Card<GuessSummon>(),
			ModelDb.Card<GuessHeal>(),
			ModelDb.Card<GuessEscape>(),
			ModelDb.Card<GuessSleep>(),
			ModelDb.Card<GuessStun>(),
			ModelDb.Card<TellAll>(),
			ModelDb.Card<DivineEye>(),
			ModelDb.Card<KarmaForeseen>(),
			ModelDb.Card<FollowHeaven>(),
			ModelDb.Card<Verdict>(),
			ModelDb.Card<MyriadMind>(),
			ModelDb.Card<SharedPrescience>(),
			ModelDb.Card<BestowFate>(),
			ModelDb.Card<RealityReversal>(),
			ModelDb.Card<GraspFate>(),
			ModelDb.Card<Observe>(),
			ModelDb.Card<Provision>(),
			ModelDb.Card<Manifest>(),
			ModelDb.Card<Abscond>(),
			ModelDb.Card<Hourglass>(),
			ModelDb.Card<Reshuffle>(),
			ModelDb.Card<DestinyAwaits>(),
			ModelDb.Card<Trifecta>(),
			ModelDb.Card<CatchOffGuard>(),
			ModelDb.Card<GlimpseFuture>(),
			ModelDb.Card<SeeThrough>(),
			ModelDb.Card<Leverage>(),
			ModelDb.Card<ObserveHeart>(),
			ModelDb.Card<Anjali>(),
			ModelDb.Card<AvoidPeril>(),
			ModelDb.Card<StillWatch>(),
			ModelDb.Card<AskHeaven>(),
			ModelDb.Card<TraceCause>(),
			ModelDb.Card<PlaceStone>(),
			ModelDb.Card<EnlightenFate>(),
			ModelDb.Card<FinalDecree>(),
			ModelDb.Card<OmenLash>(),
			ModelDb.Card<RewriteFate>(),
			ModelDb.Card<WheelOfHeaven>(),
			ModelDb.Card<PrayerWish>(),
			ModelDb.Card<AskHeavenAttack>(),
			ModelDb.Card<AskHeavenOther>(),
			ModelDb.Card<RewriteChoiceDelete>(),
			ModelDb.Card<RewriteChoiceAdvance>(),
			ModelDb.Card<WishChoicePossess>(),
			ModelDb.Card<WishChoiceProtect>(),
			ModelDb.Card<WishChoiceStrike>()
		};
	}
}
